
input.onButtonPressed(Button.A, () => {
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC0))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC1))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC2))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC3))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC4))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC5))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC6))
    basic.showNumber(iKB1.iKBADC(iKBADC.ADC7))
    
})

input.onButtonPressed(Button.B, () => {
    basic.showNumber(iKB1.In(pinx.D0))
    basic.showNumber(iKB1.In(pinx.D1))
    basic.showNumber(iKB1.In(pinx.D2))
    basic.showNumber(iKB1.In(pinx.D3))
    basic.showNumber(iKB1.In(pinx.D4))
    basic.showNumber(iKB1.In(pinx.D5))
    basic.showNumber(iKB1.In(pinx.D6))
    basic.showNumber(iKB1.In(pinx.D7))
    basic.pause(1000)
    basic.showNumber(iKB1.In_p(pinx.D0))
    basic.showNumber(iKB1.In_p(pinx.D1))
    basic.showNumber(iKB1.In_p(pinx.D2))
    basic.showNumber(iKB1.In_p(pinx.D3))
    basic.showNumber(iKB1.In_p(pinx.D4))
    basic.showNumber(iKB1.In_p(pinx.D5))
    basic.showNumber(iKB1.In_p(pinx.D6))
    basic.showNumber(iKB1.In_p(pinx.D7))
})

input.onButtonPressed(Button.AB, () => {
    iKB1.out(pinx.D0, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D1, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D2, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D3, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D4, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D5, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D6, st.ON)
    basic.pause(500)
    iKB1.out(pinx.D7, st.ON)
    basic.pause(1000)
    iKB1.out(pinx.D0, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D1, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D2, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D3, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D4, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D5, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D6, st.OFF)
    basic.pause(500)
    iKB1.out(pinx.D7, st.OFF)
    
})

iKB1.fd(50)
basic.pause(1000)
iKB1.bk(50)
basic.pause(1000)
iKB1.sl(50)
basic.pause(1000)
iKB1.sr(50)
basic.pause(1000)
iKB1.tl(50)
basic.pause(1000)
iKB1.tr(50)
basic.pause(1000)
iKB1.ao()




